### ISSUE TITLE
avancement

### ISSUE THREAD

**Issue by ucef8233** [ucef8233/manage#6]
merci de répondre au issues crée svp pour savoir votre état t'avancement

**Comment by IMANE-code** [comment]
me reste que le slider je suis en cours de documentation pour le finaliser

**Comment by isqmail** [comment]
moi je veux fini l footer aujourd'hui  i ussi j' ai un problem de documentation ou Js svp donner moi une lien pour avancé bien

**Comment by ILLUUUMII** [comment]
maintenant je travaille sur le footer
